export type SeedCollectionPoint = {
  name: string
  city: string
  address: string
  type: "head_office" | "depot" | "retail_partner"
  source_url?: string
  sort_order?: number
}

const FARM_CITY_URL = "https://thedirectory.co.zw/company.cfm?companyid=7288"

/** Default collection points seeded when the table is empty. */
export const COLLECTION_POINTS_SEED: SeedCollectionPoint[] = [
  // Head Office
  {
    name: "ARDA Seeds Head Office",
    city: "Harare",
    address: "3 Mchlery, Eastlea, Harare, Zimbabwe",
    type: "head_office",
    sort_order: 0,
  },

  // Northern / Mashonaland depots (GMB)
  { name: "Aspindale Depot", city: "Harare", address: "Number 10 Kambuzuma Road, Aspindale", type: "depot" },
  { name: "Chitungwiza Depot", city: "Chitungwiza", address: "Tilcor Industries, Zengeza, Chitungwiza", type: "depot" },
  { name: "Cleveland Depot", city: "Harare", address: "Number 1 Delport Road, Msasa, Harare", type: "depot" },
  { name: "Banket Depot", city: "Banket", address: "Number 9 Silo Road, Banket", type: "depot" },
  { name: "Chegutu Depot", city: "Chegutu", address: "Stand 248-250 Warwick Road, Industrial Site, Chegutu", type: "depot" },
  { name: "Chinhoyi Depot", city: "Chinhoyi", address: "86 Manchester Rd, Chinhoyi", type: "depot" },
  { name: "Doma Depot", city: "Doma", address: "Stand number 10, Doma", type: "depot" },
  { name: "Kadoma Depot", city: "Kadoma", address: "306 Derby Road, Industrial Site, Kadoma", type: "depot" },
  { name: "Kariba Depot", city: "Kariba", address: "Stand 1063 & 1072 Gawa Chawara, Kariba", type: "depot" },
  { name: "Karoi Depot", city: "Karoi", address: "Stand number 792, Karoi", type: "depot" },
  { name: "Lionsden Depot", city: "Chinhoyi", address: "Lionden, c/o P O Box 295, Chinhoyi", type: "depot" },
  { name: "Magunje Depot", city: "Magunje", address: "Magunje Growth Point, Hurungwe", type: "depot" },
  { name: "Mamina Depot", city: "Mamina", address: "Mhondoro Ngezi, Mamina", type: "depot" },
  { name: "Mhangura Depot", city: "Mhangura", address: "Plot 1 Platue Farm, Mhangura", type: "depot" },
  { name: "Mhondoro Depot", city: "Mhondoro", address: "GMB Mhondoro, Box 39 Mubaira", type: "depot" },
  { name: "Mudzimu Depot", city: "Mudzimu", address: "Stand No. 49 Mudzimu T/Ship, Magunje", type: "depot" },
  { name: "Mukwichi Depot", city: "Karoi", address: "Kazangarare Growth Point, Hurungwe", type: "depot" },
  { name: "Murombedzi Depot", city: "Murombedzi", address: "Stand 708 Phase 11, Robert Mugabe Highway", type: "depot" },
  { name: "Norton Depot", city: "Norton", address: "222 Endeavour Rd, Norton", type: "depot" },
  { name: "Raffingora Depot", city: "Raffingora", address: "Stand No. 102155 Kamwaza T/Ship, Raffingora", type: "depot" },
  { name: "Sanyati Depot", city: "Sanyati", address: "Stand 957 Sanyati Industries, Sanyati", type: "depot" },
  { name: "Vuti Depot", city: "Vuti", address: "Stand 15 Vuti T/ship", type: "depot" },
  { name: "Bindura Depot", city: "Bindura", address: "1 Long Acres Road, Bindura", type: "depot" },
  { name: "Centenary Depot", city: "Centenary", address: "Box 6, Centenary", type: "depot" },
  { name: "Chiweshe Depot", city: "Chiweshe", address: "Msonedi Drive, Chiweshe", type: "depot" },
  { name: "Concession Depot", city: "Concession", address: "706 Amandas Avenue, Concession", type: "depot" },
  { name: "Glendale Depot", city: "Glendale", address: "Main Street, Lot 2 Farm 10, Glendale", type: "depot" },
  { name: "Guruve Depot", city: "Guruve", address: "Stand 221 Guruve Road, Guruve", type: "depot" },
  { name: "Kachuta Depot", city: "Kachuta", address: "Kachuta Road, Kachuta", type: "depot" },
  { name: "Kamutsenzere Depot", city: "Kamutsenzere", address: "GMB Chiswiti Rd, Kamutsenzere", type: "depot" },
  { name: "Mushumbi Depot", city: "Mushumbi", address: "GMB Mushumbi", type: "depot" },
  { name: "Mt Darwin Depot", city: "Mt Darwin", address: "Mt Darwin town centre", type: "depot" },
  { name: "Mvurwi Depot", city: "Mvurwi", address: "Lot 38 of Lot 3, Mvurwi", type: "depot" },
  { name: "Rushinga Depot", city: "Rushinga", address: "Rushinga business centre", type: "depot" },
  { name: "Shamva Depot", city: "Shamva", address: "Carse Farm, Tafuna, Shamva", type: "depot" },

  // Eastern region depots
  { name: "Chivhu Depot", city: "Chivhu", address: "218-220 Jameson Street, Chivhu", type: "depot" },
  { name: "Kotwa Depot", city: "Kotwa", address: "Industrial Area, Box 20 Kotwa", type: "depot" },
  { name: "Marondera Depot", city: "Marondera", address: "6 Antwearp Road, Industrial Area, Marondera", type: "depot" },
  { name: "Murewa Depot", city: "Murewa", address: "Hurudza Road, Murewa Industrial Site", type: "depot" },
  { name: "Mutoko Depot", city: "Mutoko", address: "No. 127 Nyamuzizi Road, Mutoko", type: "depot" },
  { name: "Sadza Depot", city: "Sadza", address: "Box 16 Sadza Growth Point", type: "depot" },
  { name: "Wedza Depot", city: "Wedza", address: "Box 94 Wedza Growth Point", type: "depot" },
  { name: "Bazely Bridge Depot", city: "Bazely Bridge", address: "Stand No 139, Bazely Bridge", type: "depot" },
  { name: "Buhera Depot", city: "Buhera", address: "Box 13 Buhera", type: "depot" },
  { name: "Chiendambuya Depot", city: "Chiendambuya", address: "Stand 3830 Chiendambuya Growth Point", type: "depot" },
  { name: "Chimanimani Depot", city: "Chimanimani", address: "Ward 17 Biriri, Chimanimani", type: "depot" },
  { name: "Chinyudze Depot", city: "Headlands", address: "Box 128 Headlands", type: "depot" },
  { name: "Chipinge Depot", city: "Chipinge", address: "Stand 241 Ferreira, Chipinge", type: "depot" },
  { name: "Dewedzo Depot", city: "Rusape", address: "St Bedes Growth Point, Box 97 Rusape", type: "depot" },
  { name: "Masvosva Depot", city: "Rusape", address: "Box 94, Rusape", type: "depot" },
  { name: "Middle Sabi Depot", city: "Middle Sabi", address: "Block 27 ARDA Estates, Middle Sabi", type: "depot" },
  { name: "Mutare Grain Depot", city: "Mutare", address: "Nyakamete Industrial Area, 5065 Grimsby Close", type: "depot" },
  { name: "Mutasa Depot", city: "Mutasa", address: "51 Chinyika Rural Service Centre", type: "depot" },
  { name: "Nyanga Depot", city: "Nyanga", address: "Box 160 Nyanga", type: "depot" },
  { name: "Rusape Depot", city: "Rusape", address: "Stand 405 Chimurenga Rd, Rusape", type: "depot" },
  { name: "Timbermills Depot", city: "Headlands", address: "Farm No. 18 Fair Field, Headlands", type: "depot" },
  { name: "Chiredzi Depot", city: "Chiredzi", address: "Nandi Siding, Box 83 Chiredzi", type: "depot" },
  { name: "Chivi Depot", city: "Chivi", address: "Box 28 Chivi", type: "depot" },
  { name: "Gutu Depot", city: "Gutu", address: "Stand 200 Chatsworth Road, Gutu", type: "depot" },
  { name: "Jerera Depot", city: "Jerera", address: "Stand 495 Jerera Growth Point", type: "depot" },
  { name: "Makambe Depot", city: "Makambe", address: "Stand 1 Makambe Siding, Chiredzi", type: "depot" },
  { name: "Masvingo Depot", city: "Masvingo", address: "Stand 960-1 Mineral Road, Masvingo", type: "depot" },
  { name: "Nyika Depot", city: "Nyika", address: "Stand 2 Duma Location, Nyika", type: "depot" },
  { name: "Rutenga Depot", city: "Rutenga", address: "Stand Ca2089 Mwenezi", type: "depot" },

  // Southern region depots
  { name: "Bulawayo Depot", city: "Bulawayo", address: "13815 Sheffield Street / Off Masiyepambili Road, Bulawayo", type: "depot" },
  { name: "Binga Depot", city: "Binga", address: "Bag 5710, Binga", type: "depot" },
  { name: "Hwange Depot", city: "Hwange", address: "602 Derby Drive, Hwange", type: "depot" },
  { name: "Lupane Depot", city: "Lupane", address: "Stand 1741 Industrial Sites, Lupane", type: "depot" },
  { name: "Lusulu Depot", city: "Lusulu", address: "Stand No. 2, Lusulu Business Centre", type: "depot" },
  { name: "Nkayi Depot", city: "Nkayi", address: "Stand 970 Nkayi Growth Point", type: "depot" },
  { name: "Tsholotsho Depot", city: "Tsholotsho", address: "Stand 1643 Tsholotsho Business Centre", type: "depot" },
  { name: "Beitbridge Depot", city: "Beitbridge", address: "Stand 1388 Light Industrial Area, Beitbridge", type: "depot" },
  { name: "Filabusi Depot", city: "Filabusi", address: "Light Industrial Area, Filabusi", type: "depot" },
  { name: "Gwanda Depot", city: "Gwanda", address: "612 Light Industrial Site, Gwanda", type: "depot" },
  { name: "Maphisa Depot", city: "Maphisa", address: "Arda Road, Fouch, Maphisa", type: "depot" },
  { name: "Plumtree Depot", city: "Plumtree", address: "91 Mill Road, Plumtree", type: "depot" },
  { name: "Charandura Depot", city: "Charandura", address: "Charandura Growth Point", type: "depot" },
  { name: "Gokwe Depot", city: "Gokwe", address: "Stand 1163-72 Mapfungautsi Light Industrial Area, Gokwe", type: "depot" },
  { name: "Gweru Depot", city: "Gweru", address: "Number 4 Hull Road, Heavy Industrial Site, Gweru", type: "depot" },
  { name: "Kwekwe Depot", city: "Kwekwe", address: "Number 1 Faraday Street, Kwekwe", type: "depot" },
  { name: "Manoti Depot", city: "Manoti", address: "Manoti Business Centre, Gokwe South", type: "depot" },
  { name: "Mataga Depot", city: "Mataga", address: "Mataga Growth Point", type: "depot" },
  { name: "Nembudziya Depot", city: "Nembudziya", address: "Mtora Nembudziya Growth Point", type: "depot" },
  { name: "Tongogara Depot", city: "Tongogara", address: "154 Tongogara Growth Point, Shurugwi", type: "depot" },
  { name: "Zhombe Depot", city: "Zhombe", address: "Box 233 Kwekwe (Zhombe)", type: "depot" },
  { name: "Zvishavane Depot", city: "Zvishavane", address: "Stand 1834 Noelvale Road, Zvishavane", type: "depot" },

  // Farm & City Centre branches (The Directory)
  { name: "Farm & City — Banket", city: "Banket", address: "3 Wilmar Park, Banket", type: "retail_partner", source_url: FARM_CITY_URL },
  { name: "Farm & City — Beatrice", city: "Beatrice", address: "1 Barrington, Harare South", type: "retail_partner", source_url: FARM_CITY_URL },
  { name: "Farm & City — Bindura", city: "Bindura", address: "111 Thurlow Avenue, Bindura", type: "retail_partner", source_url: FARM_CITY_URL },
  { name: "Farm & City — Bulawayo (Jason Moyo)", city: "Bulawayo", address: "102 Jason Moyo Avenue, Bulawayo", type: "retail_partner", source_url: FARM_CITY_URL },
  { name: "Farm & City — Bulawayo (Lobengula)", city: "Bulawayo", address: "99 Lobengula Street, Bulawayo", type: "retail_partner", source_url: FARM_CITY_URL },
  { name: "Farm & City — Checheche", city: "Checheche", address: "Stand 277/9, Checheche", type: "retail_partner", source_url: FARM_CITY_URL },
  { name: "Farm & City — Chegutu", city: "Chegutu", address: "120 Queens Street, Chegutu", type: "retail_partner", source_url: FARM_CITY_URL },
  { name: "Farm & City — Chinhoyi", city: "Chinhoyi", address: "Cnr Magamba Way / Robert Mugabe Road, Chinhoyi", type: "retail_partner", source_url: FARM_CITY_URL },
  { name: "Farm & City — Chipangayi", city: "Chipangayi", address: "Stand 130 Tropical Building, Chipangayi", type: "retail_partner", source_url: FARM_CITY_URL },
  { name: "Farm & City — Chipinge", city: "Chipinge", address: "Stand 310 Joubert Street, Chipinge", type: "retail_partner", source_url: FARM_CITY_URL },
  { name: "Farm & City — Chiredzi", city: "Chiredzi", address: "5504 Lion Drive, Chiredzi", type: "retail_partner", source_url: FARM_CITY_URL },
  { name: "Farm & City — Glendale", city: "Glendale", address: "1 Main Square, Glendale", type: "retail_partner", source_url: FARM_CITY_URL },
  { name: "Farm & City — Gokwe", city: "Gokwe", address: "Stand 11 Mateta Road, Gokwe", type: "retail_partner", source_url: FARM_CITY_URL },
  { name: "Farm & City — Guruve", city: "Guruve", address: "Stand 56 Shamwari Store, Guruve", type: "retail_partner", source_url: FARM_CITY_URL },
  { name: "Farm & City — Gweru (3rd Street)", city: "Gweru", address: "Stand 6768 3rd Street, Gweru", type: "retail_partner", source_url: FARM_CITY_URL },
  { name: "Farm & City — Gweru (Tongogara)", city: "Gweru", address: "29 Josiah Tongogara Avenue, Gweru", type: "retail_partner", source_url: FARM_CITY_URL },
  { name: "Farm & City — Harare Hardware", city: "Harare", address: "Cnr 4th Street / Robson Manyika Avenue, Harare", type: "retail_partner", source_url: FARM_CITY_URL },
  { name: "Farm & City — Hauna", city: "Hauna", address: "Hauna Township", type: "retail_partner", source_url: FARM_CITY_URL },
  { name: "Farm & City — Head Office", city: "Harare", address: "1 Wynne Street, Harare", type: "retail_partner", source_url: FARM_CITY_URL },
  { name: "Farm & City — Horticulture Centre", city: "Harare", address: "1 Wynne Street, Harare", type: "retail_partner", source_url: FARM_CITY_URL },
  { name: "Farm & City — Kadoma", city: "Kadoma", address: "333/4 Josiah Tongogara Avenue, Kadoma", type: "retail_partner", source_url: FARM_CITY_URL },
  { name: "Farm & City — Karoi", city: "Karoi", address: "16 Fred Johnson Road, Karoi", type: "retail_partner", source_url: FARM_CITY_URL },
  { name: "Farm & City — Kwekwe", city: "Kwekwe", address: "Industrial Site, Kwekwe", type: "retail_partner", source_url: FARM_CITY_URL },
  { name: "Farm & City — Marondera", city: "Marondera", address: "5 Birmingham Road, Marondera", type: "retail_partner", source_url: FARM_CITY_URL },
  { name: "Farm & City — Masvingo", city: "Masvingo", address: "95 Leopold Takawira Street, Masvingo", type: "retail_partner", source_url: FARM_CITY_URL },
  { name: "Farm & City — Mbare", city: "Harare", address: "Mbare Musika, Harare", type: "retail_partner", source_url: FARM_CITY_URL },
  { name: "Farm & City — Mhangura", city: "Mhangura", address: "Stand 521 Lions Den Road, Mhangura", type: "retail_partner", source_url: FARM_CITY_URL },
  { name: "Farm & City — Mt Darwin", city: "Mt Darwin", address: "Stand 148 Muzakabani Road, Mount Darwin", type: "retail_partner", source_url: FARM_CITY_URL },
  { name: "Farm & City — Mutare", city: "Mutare", address: "5 E Avenue, Mutare", type: "retail_partner", source_url: FARM_CITY_URL },
  { name: "Farm & City — Mutoko", city: "Mutoko", address: "Stand 91-2 Chinzanga Township, Mutoko", type: "retail_partner", source_url: FARM_CITY_URL },
  { name: "Farm & City — Mvurwi", city: "Mvurwi", address: "Cnr Catham Avenue / Ferguson Road, Mvurwi", type: "retail_partner", source_url: FARM_CITY_URL },
  { name: "Farm & City — Nyanga", city: "Nyanga", address: "Roachdale, Nyanga", type: "retail_partner", source_url: FARM_CITY_URL },
  { name: "Farm & City — Nyazura", city: "Nyazura", address: "Stand 2-3 Town Centre, Nyazura", type: "retail_partner", source_url: FARM_CITY_URL },
  { name: "Farm & City — Odzi", city: "Odzi", address: "Stand 57 Odzi Township", type: "retail_partner", source_url: FARM_CITY_URL },
  { name: "Farm & City — Rusape", city: "Rusape", address: "70 Magamba Street, Rusape", type: "retail_partner", source_url: FARM_CITY_URL },
  { name: "Farm & City — Sanyati", city: "Sanyati", address: "Sanyati Township", type: "retail_partner", source_url: FARM_CITY_URL },
  { name: "Farm & City — Tengwe", city: "Tengwe", address: "Stand 40, Tengwe", type: "retail_partner", source_url: FARM_CITY_URL },
  { name: "Farm & City — Vet Centre", city: "Harare", address: "1 Wynne Street, Harare", type: "retail_partner", source_url: FARM_CITY_URL },
  { name: "Farm & City — Zvishavane", city: "Zvishavane", address: "Stand 1, Shop 3 & 4 Ireland Road, Zvishavane", type: "retail_partner", source_url: FARM_CITY_URL },

  // Electrosales (cities from contact page)
  { name: "Electrosales — Harare", city: "Harare", address: "Harare", type: "retail_partner" },
  { name: "Electrosales — Bulawayo", city: "Bulawayo", address: "Bulawayo", type: "retail_partner" },
  { name: "Electrosales — Mutare", city: "Mutare", address: "Mutare", type: "retail_partner" },
]
